name: Build, Test, and Release

on:
  # run when action is manually triggered
  workflow_dispatch:
  # run on pushes to release branch
  push:
    branches: [release]
  # run daily at 08:00am UTC (on the default or base branch)
  # https://crontab.guru/#0_8_*_*_*
  schedule:
    - cron: "0 8 * * *"

jobs:
  build-test-release:
    name: Build, Test, and Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Load pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: py-${{ hashFiles('converter/textbook-converter/requirements.txt') }}-${{ hashFiles('converter/textbook-converter/requirements-test.txt') }}

      - name: Install Python dependencies
        run: pip install -r converter/textbook-converter/requirements.txt -r converter/textbook-converter/requirements-test.txt

      # - name: Notebook tests
      #   run: npm run test:nb

      - name: Build
        run: npm run build

      # - name: Cypress tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm start
      #     wait-on: 'http://localhost:8080/health'

      # We remove the Dockerfile because when there is a Dockerfile in the
      # current directory, Google App Engine try to use it.
      - name: Remove Dockerfile
        run: rm -f Dockerfile

      - name: Deploy to AppEngine
        uses: google-github-actions/deploy-appengine@main
        with:
          # The GCLOUD_SERVICE_ACCOUNT secret is defined in the GitHub repo.
          # It needs the following permissions
          #  - roles/appengine.appAdmin
          #  - roles/iam.serviceAccountUser
          #  - roles/compute.storageAdmin
          #  - cloudbuild.builds.editor
          credentials: ${{secrets.GCLOUD_SERVICE_ACCOUNT}}
          deliverables: app.yaml
          # qiskit-web is the Google Cloud App ID provided by Mathigon
          project_id: qiskit-web
